In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [164]:
Z=np.array([0,2])
A=np.array([1,2])

In [165]:
def C(i):
    return np.sum(A*Z**i)

In [166]:
def M(n,n0):
    return np.array([[C(n0+i+j) for i in range(n)] for j in range(n)])

In [167]:
M(10,0)

array([[     3,      4,      8,     16,     32,     64,    128,    256,
           512,   1024],
       [     4,      8,     16,     32,     64,    128,    256,    512,
          1024,   2048],
       [     8,     16,     32,     64,    128,    256,    512,   1024,
          2048,   4096],
       [    16,     32,     64,    128,    256,    512,   1024,   2048,
          4096,   8192],
       [    32,     64,    128,    256,    512,   1024,   2048,   4096,
          8192,  16384],
       [    64,    128,    256,    512,   1024,   2048,   4096,   8192,
         16384,  32768],
       [   128,    256,    512,   1024,   2048,   4096,   8192,  16384,
         32768,  65536],
       [   256,    512,   1024,   2048,   4096,   8192,  16384,  32768,
         65536, 131072],
       [   512,   1024,   2048,   4096,   8192,  16384,  32768,  65536,
        131072, 262144],
       [  1024,   2048,   4096,   8192,  16384,  32768,  65536, 131072,
        262144, 524288]])

In [168]:
n=2
M0,M1=M(n,0),M(n,1)


In [169]:
np.set_printoptions(suppress=True)

In [170]:
M0

array([[3, 4],
       [4, 8]])

In [171]:
X=np.linalg.solve(M0,M1)

In [172]:
np.linalg.matrix_rank(M0)

2

In [173]:
np.linalg.eigvals(M0)

array([ 0.78300943, 10.21699057])

In [174]:
X

array([[0., 0.],
       [1., 2.]])

In [154]:
np.linalg.eigvals(X)

array([2., 3.])